name: Run Tests and Checks
on: push

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
            
        steps:
            - uses: actions/checkout@v4

            - name: Setup Python ${{ matrix.python_version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python_version }}
                
            - name: Setup Poetry
              run: pip install --user poetry
                
            - name: Install dependencies
              run: poetry install
        
            - name: Check Package Lockfile
              run: poetry check

            - name: Run Linting
              run: poetry run pylint connman_cli tests
            
            - name: Run Formatting
              run: poetry run black --check connman_cli tests

            - name: Run Tests
              run: poetry run pytest || exit 0
            
            - name: Build Wheel
              run: poetry build
            
            - name: Save Build Output
              uses: actions/upload-artifact@v3
              with:
                name: build-output-py${{ matrix.python_version }}
                path: dist/*
